# Generated by Django 6.0.6 on 2026-07-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_character_accountid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('died_at', models.DateTimeField()),
                ('killers', models.TextField()),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='bot.character')),
            ],
            options={
                'ordering': ['-died_at'],
            },
        ),
    ]
