# Generated by Django 6.0.6 on 2026-07-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_characterdeath'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=32, unique=True)),
                ('alert_channel_id', models.CharField(max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_guilds', to='bot.discordserversettings')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('settings', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WatchedWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_worlds', to='bot.discordserversettings')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('settings', 'name')},
            },
        ),
    ]
